### ISSUE TITLE
Clickable bars in Bar Chart

### ISSUE THREAD

**Issue by dg-datavisyn** [datavisyn/tdp_core#629] opened 2022-02-16 10:07 UTC
* Release number or git hash: Version: 10.0.1-SNAPSHOT
* Web browser version and OS: Google Chrome Version 98.0.4758.102 (Offizieller Build) (64-Bit) on Win 11
* Environment (local or deployed): https://ordino.dev.app.datavisyn.io/

### Steps to reproduce

1. Open a tissue data ranking
2. Open the Vis panel
3. Create a scatter plot

### Observed behavior
* I can't make a selection by clicking on the bars

### Expected behavior
* As a user I want to be able to click on a bar and the corresponding data in the ranking is selected. With CRTL I want to be able to select multiple bars as well.

**Comment by dvzacharycutler** [comment] 2022-05-31 14:17
duplicate of https://github.com/datavisyn/reprovisyn/issues/294

**Closed by dvzacharycutler** 2022-05-31 14:17 UTC
Labels: type: feature, package: vis
